-- MisArte Digital v1.3.2 — Produtos
create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  categoria_id bigint not null references public.categorias(id) on delete cascade,
  nome text not null,
  descricao text,
  preco numeric(10,2),
  status text not null default 'disponivel' check (status in ('disponivel','indisponivel')),
  destaque boolean not null default false,
  ordem integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists produtos_categoria_id_idx on public.produtos(categoria_id);
create index if not exists produtos_categoria_ordem_idx on public.produtos(categoria_id,ordem);
alter table public.produtos enable row level security;
drop policy if exists "misarte produtos select" on public.produtos;
drop policy if exists "misarte produtos insert" on public.produtos;
drop policy if exists "misarte produtos update" on public.produtos;
drop policy if exists "misarte produtos delete" on public.produtos;
create policy "misarte produtos select" on public.produtos for select to authenticated using ((auth.jwt()->>'email')='miscristiane@gmail.com');
create policy "misarte produtos insert" on public.produtos for insert to authenticated with check ((auth.jwt()->>'email')='miscristiane@gmail.com');
create policy "misarte produtos update" on public.produtos for update to authenticated using ((auth.jwt()->>'email')='miscristiane@gmail.com') with check ((auth.jwt()->>'email')='miscristiane@gmail.com');
create policy "misarte produtos delete" on public.produtos for delete to authenticated using ((auth.jwt()->>'email')='miscristiane@gmail.com');
create or replace function public.set_produtos_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists produtos_set_updated_at on public.produtos;
create trigger produtos_set_updated_at before update on public.produtos for each row execute function public.set_produtos_updated_at();
