-- MisArte Digital v1.3.0 — Gestão de Catálogos
-- Execute uma única vez em Supabase > SQL Editor > New query > Run

create table if not exists public.catalogos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  nome text not null,
  tipo text not null default 'cardapio',
  descricao text,
  status text not null default 'rascunho'
    check (status in ('rascunho','publicado','arquivado')),
  destaque boolean not null default false,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists catalogos_cliente_id_idx
  on public.catalogos(cliente_id);

create index if not exists catalogos_cliente_ordem_idx
  on public.catalogos(cliente_id, ordem);

alter table public.catalogos enable row level security;

drop policy if exists "misarte catalogos select" on public.catalogos;
drop policy if exists "misarte catalogos insert" on public.catalogos;
drop policy if exists "misarte catalogos update" on public.catalogos;
drop policy if exists "misarte catalogos delete" on public.catalogos;

create policy "misarte catalogos select"
on public.catalogos for select
to authenticated
using ((auth.jwt() ->> 'email') = 'miscristiane@gmail.com');

create policy "misarte catalogos insert"
on public.catalogos for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'miscristiane@gmail.com');

create policy "misarte catalogos update"
on public.catalogos for update
to authenticated
using ((auth.jwt() ->> 'email') = 'miscristiane@gmail.com')
with check ((auth.jwt() ->> 'email') = 'miscristiane@gmail.com');

create policy "misarte catalogos delete"
on public.catalogos for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'miscristiane@gmail.com');

create or replace function public.set_catalogos_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists catalogos_set_updated_at on public.catalogos;

create trigger catalogos_set_updated_at
before update on public.catalogos
for each row execute function public.set_catalogos_updated_at();
