-- MisArte Digital v1.3.1 — Categorias
create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  catalogo_id bigint not null references public.catalogos(id) on delete cascade,
  nome text not null,
  descricao text,
  status text not null default 'ativa' check (status in ('ativa','oculta')),
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists categorias_catalogo_id_idx on public.categorias(catalogo_id);
create index if not exists categorias_catalogo_ordem_idx on public.categorias(catalogo_id,ordem);
alter table public.categorias enable row level security;
drop policy if exists "misarte categorias select" on public.categorias;
drop policy if exists "misarte categorias insert" on public.categorias;
drop policy if exists "misarte categorias update" on public.categorias;
drop policy if exists "misarte categorias delete" on public.categorias;
create policy "misarte categorias select" on public.categorias for select to authenticated using ((auth.jwt()->>'email')='miscristiane@gmail.com');
create policy "misarte categorias insert" on public.categorias for insert to authenticated with check ((auth.jwt()->>'email')='miscristiane@gmail.com');
create policy "misarte categorias update" on public.categorias for update to authenticated using ((auth.jwt()->>'email')='miscristiane@gmail.com') with check ((auth.jwt()->>'email')='miscristiane@gmail.com');
create policy "misarte categorias delete" on public.categorias for delete to authenticated using ((auth.jwt()->>'email')='miscristiane@gmail.com');
create or replace function public.set_categorias_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists categorias_set_updated_at on public.categorias;
create trigger categorias_set_updated_at before update on public.categorias for each row execute function public.set_categorias_updated_at();
