-- MisArte Digital v1.7.0 — Editor visual de catálogos
-- Execute uma única vez em Supabase > SQL Editor > New query > Run

create table if not exists public.catalogo_paginas (
  id bigint generated by default as identity primary key,
  catalogo_id bigint not null references public.catalogos(id) on delete cascade,
  nome text not null default 'Nova página',
  tipo text not null default 'conteudo' check (tipo in ('capa','conteudo')),
  fundo_url text,
  largura integer not null default 1080,
  altura integer not null default 1920,
  ordem integer not null default 1,
  status text not null default 'ativa' check (status in ('ativa','oculta')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pagina_elementos (
  id bigint generated by default as identity primary key,
  pagina_id bigint not null references public.catalogo_paginas(id) on delete cascade,
  tipo text not null default 'botao' check (tipo in ('botao','texto','imagem')),
  conteudo text,
  imagem_url text,
  posicao_x numeric(6,3) not null default 10,
  posicao_y numeric(6,3) not null default 10,
  largura numeric(6,3) not null default 40,
  altura numeric(6,3) not null default 8,
  destino_tipo text not null default 'nenhum'
    check (destino_tipo in ('nenhum','pagina','categoria','produto','url')),
  destino_id bigint,
  destino_url text,
  estilos jsonb not null default '{}'::jsonb,
  ordem integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists catalogo_paginas_catalogo_idx on public.catalogo_paginas(catalogo_id,ordem);
create index if not exists pagina_elementos_pagina_idx on public.pagina_elementos(pagina_id,ordem);

alter table public.catalogo_paginas enable row level security;
alter table public.pagina_elementos enable row level security;

drop policy if exists "misarte catalogo paginas admin" on public.catalogo_paginas;
create policy "misarte catalogo paginas admin" on public.catalogo_paginas
for all to authenticated
using ((auth.jwt()->>'email')='miscristiane@gmail.com')
with check ((auth.jwt()->>'email')='miscristiane@gmail.com');

drop policy if exists "misarte pagina elementos admin" on public.pagina_elementos;
create policy "misarte pagina elementos admin" on public.pagina_elementos
for all to authenticated
using ((auth.jwt()->>'email')='miscristiane@gmail.com')
with check ((auth.jwt()->>'email')='miscristiane@gmail.com');

create or replace function public.set_editor_visual_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end;
$$;

drop trigger if exists catalogo_paginas_updated_at on public.catalogo_paginas;
create trigger catalogo_paginas_updated_at before update on public.catalogo_paginas
for each row execute function public.set_editor_visual_updated_at();

drop trigger if exists pagina_elementos_updated_at on public.pagina_elementos;
create trigger pagina_elementos_updated_at before update on public.pagina_elementos
for each row execute function public.set_editor_visual_updated_at();

