(() => {
const db=window.misarteSupabase,p=new URLSearchParams(location.search),clientId=p.get("cliente"),catalogId=p.get("catalogo");
const $=s=>document.querySelector(s),e={loader:$("#pageLoader"),app:$("#dashboardApp"),email:$("#userEmail"),logout:$("#logoutButton"),menu:$("#menuButton"),sidebar:$(".sidebar"),clientCrumb:$("#clientBreadcrumb"),catalogCrumb:$("#catalogBreadcrumb"),catalogName:$("#catalogName"),catalogMeta:$("#catalogMeta"),total:$("#categoryTotal"),active:$("#categoryActive"),hidden:$("#categoryHidden"),search:$("#searchInput"),statusFilter:$("#statusFilter"),sortFilter:$("#sortFilter"),state:$("#categoryState"),list:$("#categoryList"),newBtn:$("#newCategoryButton"),drawer:$("#categoryDrawer"),backdrop:$("#drawerBackdrop"),close:$("#closeDrawerButton"),cancel:$("#cancelButton"),form:$("#categoryForm"),id:$("#categoryId"),name:$("#categoryName"),status:$("#categoryStatus"),order:$("#categoryOrder"),description:$("#categoryDescription"),title:$("#drawerTitle"),message:$("#formMessage"),save:$("#saveButton"),modal:$("#confirmModal"),confirmText:$("#confirmText"),cancelDelete:$("#cancelDeleteButton"),confirmDelete:$("#confirmDeleteButton"),toast:$("#toast")};
let rows=[],target=null;
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const toast=(m,t="success")=>{e.toast.textContent=m;e.toast.className=`toast ${t}`;e.toast.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.toast.hidden=true,3000)};
const filtered=()=>{const q=norm(e.search.value),s=norm(e.statusFilter.value),sort=e.sortFilter.value;return rows.filter(x=>(!q||norm(`${x.nome} ${x.descricao}`).includes(q))&&(!s||norm(x.status)===s)).sort((a,b)=>sort==="nome"?String(a.nome).localeCompare(String(b.nome),"pt-BR"):sort==="recentes"?new Date(b.created_at)-new Date(a.created_at):Number(a.ordem||0)-Number(b.ordem||0))};
function render(){e.total.textContent=rows.length;e.active.textContent=rows.filter(x=>x.status==="ativa").length;e.hidden.textContent=rows.filter(x=>x.status==="oculta").length;const list=filtered();if(!list.length){e.state.textContent=rows.length?"Nenhuma categoria corresponde aos filtros.":"Nenhuma categoria cadastrada. Clique em “Nova categoria” para começar.";e.state.hidden=false;e.list.hidden=true;return}e.list.innerHTML=list.map((x,i)=>`<article class="category-row"><div class="category-order">${esc(x.ordem??i+1)}</div><div class="category-content"><div class="category-title-line"><h2>${esc(x.nome)}</h2><span class="status-badge ${x.status==="ativa"?"status-active":"status-neutral"}">${x.status==="ativa"?"Ativa":"Oculta"}</span></div><p>${esc(x.descricao||"Sem descrição.")}</p></div><div class="category-actions"><a class="button button-primary" href="./produtos.html?cliente=${encodeURIComponent(clientId)}&catalogo=${encodeURIComponent(catalogId)}&categoria=${encodeURIComponent(x.id)}">Gerenciar produtos</a><button class="button button-secondary" data-action="edit" data-id="${esc(x.id)}">Editar</button><button class="button button-text-danger" data-action="delete" data-id="${esc(x.id)}">Excluir</button></div></article>`).join("");e.state.hidden=true;e.list.hidden=false}
async function load(){const{data,error}=await db.from("categorias").select("id,catalogo_id,nome,descricao,status,ordem,created_at").eq("catalogo_id",catalogId).order("ordem",{ascending:true});if(error){e.state.textContent="Não foi possível carregar as categorias. Execute o SQL da versão v1.3.1.";toast(error.message,"error");return}rows=data||[];render()}
async function context(){const[{data:c,error:ce},{data:g,error:ge}]=await Promise.all([db.from("clientes").select("id,nome,empresa").eq("id",clientId).single(),db.from("catalogos").select("id,cliente_id,nome,tipo,status").eq("id",catalogId).eq("cliente_id",clientId).single()]);if(ce)throw ce;if(ge)throw ge;e.clientCrumb.textContent=c.nome||c.empresa||"Cliente";e.clientCrumb.href=`./cliente.html?id=${encodeURIComponent(clientId)}`;e.catalogCrumb.href=`./catalogos.html?id=${encodeURIComponent(clientId)}`;e.catalogName.textContent=g.nome;e.catalogMeta.textContent=`${g.tipo.replaceAll("_"," ")} · ${g.status}`}
function open(x=null){e.form.reset();e.id.value=x?.id||"";e.name.value=x?.nome||"";e.status.value=x?.status||"ativa";e.order.value=x?.ordem??(rows.length?Math.max(...rows.map(r=>Number(r.ordem||0)))+1:1);e.description.value=x?.descricao||"";e.title.textContent=x?"Editar categoria":"Nova categoria";e.save.textContent=x?"Salvar alterações":"Salvar categoria";e.message.textContent="";e.backdrop.hidden=false;e.drawer.classList.add("is-open");document.body.classList.add("drawer-open")}
function close(){e.drawer.classList.remove("is-open");e.backdrop.hidden=true;document.body.classList.remove("drawer-open")}
e.form.addEventListener("submit",async ev=>{ev.preventDefault();if(!e.form.checkValidity()){e.form.reportValidity();return}e.save.disabled=true;e.save.textContent="Salvando...";const payload={catalogo_id:catalogId,nome:e.name.value.trim(),descricao:e.description.value.trim()||null,status:e.status.value,ordem:Number(e.order.value||0)},id=e.id.value,q=id?db.from("categorias").update(payload).eq("id",id).eq("catalogo_id",catalogId):db.from("categorias").insert(payload),{error}=await q;e.save.disabled=false;e.save.textContent=id?"Salvar alterações":"Salvar categoria";if(error){e.message.textContent=error.message;e.message.className="form-message error";return}close();await load();toast(id?"Categoria atualizada.":"Categoria criada.")});
e.list.addEventListener("click",ev=>{const b=ev.target.closest("button[data-action]");if(!b)return;const x=rows.find(r=>String(r.id)===b.dataset.id);if(!x)return;if(b.dataset.action==="edit")open(x);else{target=x;e.confirmText.textContent=`Você está prestes a excluir “${x.nome}”.`;e.modal.hidden=false}});
e.confirmDelete.addEventListener("click",async()=>{if(!target)return;const{error}=await db.from("categorias").delete().eq("id",target.id).eq("catalogo_id",catalogId);e.modal.hidden=true;target=null;if(error){toast(error.message,"error");return}await load();toast("Categoria excluída.")});
e.cancelDelete.addEventListener("click",()=>{e.modal.hidden=true;target=null});
e.newBtn.addEventListener("click",()=>open());e.close.addEventListener("click",close);e.cancel.addEventListener("click",close);e.backdrop.addEventListener("click",close);
[e.search,e.statusFilter,e.sortFilter].forEach(c=>c.addEventListener(c===e.search?"input":"change",render));
e.menu.addEventListener("click",()=>e.sidebar.classList.toggle("is-open"));e.logout.addEventListener("click",async()=>{await db.auth.signOut();location.replace("./login.html")});
(async()=>{if(!clientId||!catalogId){location.replace("./clientes.html");return}const{data}=await db.auth.getSession();if(!data.session){location.replace("./login.html");return}e.email.textContent=data.session.user.email||"Usuária autenticada";await context();e.loader.hidden=true;e.app.hidden=false;await load()})().catch(err=>{console.error(err);e.loader.hidden=true;e.app.hidden=false;e.state.textContent=err.message||"Não foi possível abrir esta área."});
})();